%% Electric Propulsion System - Model Setup for Data Logging
% This script helps configure your Simscape model for fault dataset generation
%
% Run this BEFORE running simscape_fault_dataset_generator.m
%
% Author: Electric Propulsion Digital Twin
% Date: 2024

clear; clc; close all;

%% ========================================================================
%  MODEL CONFIGURATION INSTRUCTIONS
%  ========================================================================

fprintf('========================================\n');
fprintf('  Model Setup for Dataset Generation\n');
fprintf('========================================\n\n');

fprintf('Before running the dataset generator, configure your model:\n\n');

%% ========================================================================
%  STEP 1: ADD TO WORKSPACE BLOCKS FOR DATA LOGGING
%  ========================================================================

fprintf('STEP 1: Add "To Workspace" blocks for each signal\n');
fprintf('=========================================\n\n');

signals_to_log = {
    'Voltage',      'V_battery',    'Battery terminal voltage';
    'Current',      'I_battery',    'Battery current (from Current Sensor)';
    'omega',        'omega',        'Angular velocity (from Motion Sensor W port)';
    'Torque',       'torque',       'Propeller torque (from MATLAB Function)';
    'Thrust',       'thrust',       'Propeller thrust (from MATLAB Function)';
};

fprintf('Add these "To Workspace" blocks (Simulink → Sinks → To Workspace):\n\n');
fprintf('%-12s %-15s %s\n', 'Signal', 'Variable Name', 'Source');
fprintf('%s\n', repmat('-', 1, 60));
for i = 1:size(signals_to_log, 1)
    fprintf('%-12s %-15s %s\n', signals_to_log{i, :});
end

fprintf('\nFor each "To Workspace" block:\n');
fprintf('  1. Set "Variable name" as shown above\n');
fprintf('  2. Set "Save format" = "Timeseries"\n');
fprintf('  3. Connect to the appropriate signal line\n\n');

%% ========================================================================
%  STEP 2: MODIFY PROPELLER FUNCTION FOR EXTERNAL Kt
%  ========================================================================

fprintf('\nSTEP 2: Modify Propeller MATLAB Function for variable Kt\n');
fprintf('========================================================\n\n');

fprintf('Replace your propeller function with this version:\n\n');

propeller_code = [...
'function [Torque, Thrust] = propeller(omega, Kt_input)\n'...
'    %% Propeller model with external Kt parameter\n'...
'    %% Kt_input allows fault injection from workspace\n'...
'    \n'...
'    %% Use workspace Kt if available, otherwise use input\n'...
'    Kt = Kt_input;  %% Thrust coefficient (can be set externally)\n'...
'    Kq = 0.060;     %% Torque coefficient\n'...
'    rho = 1.225;    %% Air density (kg/m³)\n'...
'    D = 0.9;        %% Propeller diameter (m)\n'...
'    \n'...
'    %% Convert omega (rad/s) to n (rev/s)\n'...
'    n = abs(omega) / (2 * pi);\n'...
'    \n'...
'    %% Calculate torque and thrust\n'...
'    Torque = -Kq * rho * n^2 * D^5;\n'...
'    Thrust = Kt * rho * n^2 * D^4;\n'...
'end\n'];

fprintf('%s\n', propeller_code);

fprintf('Then add a Constant block with value "Kt_prop" (from workspace)\n');
fprintf('and connect it to the Kt_input of the MATLAB Function.\n\n');

%% ========================================================================
%  STEP 3: ALTERNATIVE - USE SIGNAL LOGGING
%  ========================================================================

fprintf('\nSTEP 3 (Alternative): Use Signal Logging instead of To Workspace\n');
fprintf('================================================================\n\n');

fprintf('For each signal you want to log:\n');
fprintf('  1. Right-click the signal line\n');
fprintf('  2. Select "Properties"\n');
fprintf('  3. Check "Log signal data"\n');
fprintf('  4. Enter a descriptive name (e.g., "Voltage")\n\n');

fprintf('Then in Model Settings:\n');
fprintf('  1. Go to "Data Import/Export"\n');
fprintf('  2. Check "Signal logging"\n');
fprintf('  3. Set "Signal logging name" = "logsout"\n\n');

%% ========================================================================
%  STEP 4: VERIFY BLOCK PARAMETER NAMES
%  ========================================================================

fprintf('\nSTEP 4: Verify Block Parameter Names\n');
fprintf('=====================================\n\n');

fprintf('Run this code to check your model''s parameter names:\n\n');

check_code = [...
'model_name = ''ElectricPropSys_digitalTwin'';\n'...
'load_system(model_name);\n'...
'\n'...
'%% Check Battery parameters\n'...
'battery_block = [model_name, ''/Battery''];\n'...
'battery_params = get_param(battery_block, ''DialogParameters'');\n'...
'fprintf(''Battery parameters:\\n'');\n'...
'disp(fieldnames(battery_params));\n'...
'\n'...
'%% Check Motor parameters\n'...
'motor_block = [model_name, ''/Motor & Drive''];\n'...
'motor_params = get_param(motor_block, ''DialogParameters'');\n'...
'fprintf(''Motor parameters:\\n'');\n'...
'disp(fieldnames(motor_params));\n'];

fprintf('%s\n', check_code);

%% ========================================================================
%  STEP 5: EXPECTED MODEL STRUCTURE
%  ========================================================================

fprintf('\nSTEP 5: Expected Model Structure\n');
fprintf('=================================\n\n');

model_structure = [...
'Your model should have this structure:\n\n'...
'ElectricPropSys_digitalTwin\n'...
'├── Battery                    (Simscape Battery block)\n'...
'├── Current Sensor             (Measures battery current)\n'...
'├── Voltage Sensor             (Measures battery voltage)\n'...
'├── Motor & Drive              (System-level motor block)\n'...
'├── Motion Sensor              (Measures angular velocity)\n'...
'├── Propeller                  (MATLAB Function block)\n'...
'├── Ideal Torque Source        (Applies propeller load)\n'...
'├── Throttle                   (Constant block for torque command)\n'...
'├── Electrical Reference       (Ground)\n'...
'├── Mechanical Reference       (Ground)\n'...
'├── Solver Configuration       (Required for Simscape)\n'...
'├── PS-Simulink Converters     (Signal conversion)\n'...
'└── To Workspace blocks        (Data logging)\n'...
'    ├── V_battery\n'...
'    ├── I_battery\n'...
'    ├── omega\n'...
'    ├── torque\n'...
'    └── thrust\n'];

fprintf('%s\n', model_structure);

%% ========================================================================
%  STEP 6: BLOCK PATH MAPPING
%  ========================================================================

fprintf('\nSTEP 6: Update Block Paths in Generator Script\n');
fprintf('===============================================\n\n');

fprintf('Edit simscape_fault_dataset_generator.m and update these paths:\n\n');

fprintf('battery_block = ''%s/Battery'';           %% Your battery block path\n', 'ElectricPropSys_digitalTwin');
fprintf('motor_block = ''%s/Motor & Drive'';       %% Your motor block path\n', 'ElectricPropSys_digitalTwin');
fprintf('throttle_block = ''%s/Throttle'';         %% Your throttle input block\n', 'ElectricPropSys_digitalTwin');
fprintf('propeller_block = ''%s/Propeller'';       %% Your propeller function block\n\n', 'ElectricPropSys_digitalTwin');

fprintf('To find exact block paths:\n');
fprintf('  1. Open your model\n');
fprintf('  2. Click on each block\n');
fprintf('  3. In MATLAB Command Window, type: gcb\n');
fprintf('  4. This shows the full block path\n\n');

%% ========================================================================
%  QUICK TEST SCRIPT
%  ========================================================================

fprintf('\nQUICK TEST: Run this to verify your model setup\n');
fprintf('================================================\n\n');

test_code = [...
'%% Quick test script\n'...
'model_name = ''ElectricPropSys_digitalTwin'';\n'...
'\n'...
'%% Load model\n'...
'load_system(model_name);\n'...
'fprintf(''Model loaded.\\n'');\n'...
'\n'...
'%% Set test parameters\n'...
'Kt_prop = 0.10;  %% Nominal thrust coefficient\n'...
'\n'...
'%% Run short simulation\n'...
'simOut = sim(model_name, ''StopTime'', ''2'');\n'...
'fprintf(''Simulation complete.\\n'');\n'...
'\n'...
'%% Check logged data\n'...
'try\n'...
'    V = simOut.V_battery.Data;\n'...
'    I = simOut.I_battery.Data;\n'...
'    w = simOut.omega.Data;\n'...
'    T = simOut.thrust.Data;\n'...
'    fprintf(''Logged signals found!\\n'');\n'...
'    fprintf(''  Voltage: %.1f V\\n'', mean(V(end-100:end)));\n'...
'    fprintf(''  Current: %.1f A\\n'', mean(I(end-100:end)));\n'...
'    fprintf(''  Speed: %.0f RPM\\n'', mean(w(end-100:end))*9.549);\n'...
'    fprintf(''  Thrust: %.1f N\\n'', mean(T(end-100:end)));\n'...
'catch ME\n'...
'    fprintf(''Error: %%s\\n'', ME.message);\n'...
'    fprintf(''Check your To Workspace block configuration.\\n'');\n'...
'end\n'...
'\n'...
'close_system(model_name, 0);\n'];

fprintf('%s\n', test_code);

%% ========================================================================
%  SAVE SETUP INSTRUCTIONS
%  ========================================================================

% Save instructions to file
fid = fopen('model_setup_instructions.txt', 'w');
fprintf(fid, 'Model Setup Instructions for Fault Dataset Generation\n');
fprintf(fid, '=====================================================\n\n');
fprintf(fid, '1. Add "To Workspace" blocks for: Voltage, Current, omega, Torque, Thrust\n');
fprintf(fid, '2. Modify propeller function to accept external Kt parameter\n');
fprintf(fid, '3. Verify block parameter names using get_param()\n');
fprintf(fid, '4. Update block paths in simscape_fault_dataset_generator.m\n');
fprintf(fid, '5. Run quick test to verify logging works\n');
fclose(fid);

fprintf('========================================\n');
fprintf('  Setup instructions saved!\n');
fprintf('========================================\n');
fprintf('File: model_setup_instructions.txt\n\n');
fprintf('After completing setup, run:\n');
fprintf('  >> simscape_fault_dataset_generator\n\n');